version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: paws-and-pills-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paws-and-pills-db
      POSTGRES_DB: paws-and-pills-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
